// <auto-generated />
using System;
using AirportLib.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirportLib.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250605003532_SeedUpdate")]
    partial class SeedUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("AirportLib.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedSeatNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("FlightId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCheckedIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PassengerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlightId", "PassportNumber")
                        .IsUnique();

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FlightId = 1,
                            IsCheckedIn = false,
                            PassengerName = "Bold Dorj",
                            PassportNumber = "E1234567"
                        },
                        new
                        {
                            Id = 2,
                            FlightId = 1,
                            IsCheckedIn = false,
                            PassengerName = "Saruul Bat",
                            PassportNumber = "E7654321"
                        },
                        new
                        {
                            Id = 3,
                            FlightId = 2,
                            IsCheckedIn = false,
                            PassengerName = "Tuya Chimed",
                            PassportNumber = "P9876543"
                        },
                        new
                        {
                            Id = 4,
                            FlightId = 2,
                            IsCheckedIn = false,
                            PassengerName = "Bataa Tseren",
                            PassportNumber = "E0000001"
                        },
                        new
                        {
                            Id = 5,
                            FlightId = 2,
                            IsCheckedIn = false,
                            PassengerName = "Erdene Gerel",
                            PassportNumber = "E0000002"
                        },
                        new
                        {
                            Id = 6,
                            FlightId = 3,
                            IsCheckedIn = false,
                            PassengerName = "Munkh Erkhem",
                            PassportNumber = "E0000003"
                        },
                        new
                        {
                            Id = 7,
                            FlightId = 3,
                            IsCheckedIn = false,
                            PassengerName = "Solongo Naran",
                            PassportNumber = "E0000004"
                        },
                        new
                        {
                            Id = 8,
                            FlightId = 3,
                            IsCheckedIn = false,
                            PassengerName = "Enkh Batbold",
                            PassportNumber = "E0000005"
                        },
                        new
                        {
                            Id = 9,
                            FlightId = 4,
                            IsCheckedIn = false,
                            PassengerName = "Nomin Soyol",
                            PassportNumber = "E0000006"
                        },
                        new
                        {
                            Id = 10,
                            FlightId = 4,
                            IsCheckedIn = false,
                            PassengerName = "Temuulen Dash",
                            PassportNumber = "E0000007"
                        },
                        new
                        {
                            Id = 11,
                            FlightId = 4,
                            IsCheckedIn = false,
                            PassengerName = "Bold Dorj",
                            PassportNumber = "E1234567"
                        },
                        new
                        {
                            Id = 12,
                            FlightId = 5,
                            IsCheckedIn = false,
                            PassengerName = "Saruul Bat",
                            PassportNumber = "E7654321"
                        },
                        new
                        {
                            Id = 13,
                            FlightId = 5,
                            IsCheckedIn = false,
                            PassengerName = "Tuya Chimed",
                            PassportNumber = "P9876543"
                        },
                        new
                        {
                            Id = 14,
                            FlightId = 5,
                            IsCheckedIn = false,
                            PassengerName = "Bataa Tseren",
                            PassportNumber = "E0000001"
                        },
                        new
                        {
                            Id = 15,
                            FlightId = 5,
                            IsCheckedIn = false,
                            PassengerName = "Erdene Gerel",
                            PassportNumber = "E0000002"
                        });
                });

            modelBuilder.Entity("AirportLib.Models.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArrivalCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("DepartureCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalCity = "ICN",
                            ArrivalTime = new DateTime(2024, 5, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            DepartureCity = "ULN",
                            DepartureTime = new DateTime(2024, 5, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "OM297",
                            Status = 0,
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 2,
                            ArrivalCity = "ICN",
                            ArrivalTime = new DateTime(2024, 5, 1, 16, 0, 0, 0, DateTimeKind.Utc),
                            DepartureCity = "ULN",
                            DepartureTime = new DateTime(2024, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "KE868",
                            Status = 0,
                            TotalSeats = 30
                        },
                        new
                        {
                            Id = 3,
                            ArrivalCity = "SVO",
                            ArrivalTime = new DateTime(2024, 5, 2, 13, 30, 0, 0, DateTimeKind.Utc),
                            DepartureCity = "ULN",
                            DepartureTime = new DateTime(2024, 5, 2, 9, 30, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "SU123",
                            Status = 0,
                            TotalSeats = 25
                        },
                        new
                        {
                            Id = 4,
                            ArrivalCity = "PEK",
                            ArrivalTime = new DateTime(2024, 5, 3, 10, 45, 0, 0, DateTimeKind.Utc),
                            DepartureCity = "ULN",
                            DepartureTime = new DateTime(2024, 5, 3, 7, 45, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "CA902",
                            Status = 0,
                            TotalSeats = 35
                        },
                        new
                        {
                            Id = 5,
                            ArrivalCity = "NRT",
                            ArrivalTime = new DateTime(2024, 5, 4, 15, 15, 0, 0, DateTimeKind.Utc),
                            DepartureCity = "ULN",
                            DepartureTime = new DateTime(2024, 5, 4, 11, 15, 0, 0, DateTimeKind.Utc),
                            FlightNumber = "JL508",
                            Status = 0,
                            TotalSeats = 40
                        });
                });

            modelBuilder.Entity("AirportLib.Models.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Passengers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Bold",
                            LastName = "Dorj",
                            PassportNumber = "E1234567"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Saruul",
                            LastName = "Bat",
                            PassportNumber = "E7654321"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Tuya",
                            LastName = "Chimed",
                            PassportNumber = "P9876543"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Bataa",
                            LastName = "Tseren",
                            PassportNumber = "E0000001"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Erdene",
                            LastName = "Gerel",
                            PassportNumber = "E0000002"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Munkh",
                            LastName = "Erkhem",
                            PassportNumber = "E0000003"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Solongo",
                            LastName = "Naran",
                            PassportNumber = "E0000004"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Enkh",
                            LastName = "Batbold",
                            PassportNumber = "E0000005"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Nomin",
                            LastName = "Soyol",
                            PassportNumber = "E0000006"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Temuulen",
                            LastName = "Dash",
                            PassportNumber = "E0000007"
                        });
                });

            modelBuilder.Entity("AirportLib.Models.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PassengerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PassengerId");

                    b.HasIndex("FlightId", "SeatNumber")
                        .IsUnique();

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("AirportLib.Models.Booking", b =>
                {
                    b.HasOne("AirportLib.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("AirportLib.Models.Seat", b =>
                {
                    b.HasOne("AirportLib.Models.Flight", "Flight")
                        .WithMany("Seats")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AirportLib.Models.Passenger", "AssignedPassenger")
                        .WithMany()
                        .HasForeignKey("PassengerId");

                    b.Navigation("AssignedPassenger");

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("AirportLib.Models.Flight", b =>
                {
                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
